version: '3'
services:
  # demo:
  #   image: final-year-project
  #   ports:
  #     - "8001:80" # flask app should run on 8001
  #   networks:
  #     - app
  #   depends_on:
  #     - api
  # api:
  #   image: final-year-project
  #   ports:
  #     - "5002:5000"
  #   environment:
  #     - MILVUS_ADDR=192.168.1.38
  #     - REDIS_ADDR=192.168.1.38
  #     - MILVUS_PORT=19530
  #   networks:
  #     - app
  #   depends_on:
  #     - redis
  #     - milvus

  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /mnt/redis/data:/data
    command: redis-server --appendonly yes
    networks:
      - app

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    networks:
      - app

  milvus:
    image: milvusdb/milvus:1.1.0-cpu-d050721-5e559c
    ports:
      - "19530:19530"
      - "19121:19121"
      - "8090:8080"
    volumes:
      - /mnt/milvus/db:/var/lib/milvus/db
    networks:
      - app

  milvus_admin:
    image: milvusdb/milvus-em:v0.4.2
    ports: 
      - "3000:80"
    networks:
      - app
  
networks:
  app:
    driver: bridge
